server:
  port: 8080

mybatis:
  typeAliasesPackage: com.luo.webmagic.entity
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    tk.mybatis: info
    com.clamc.mapper: info
spring:
  datasource:
    url: jdbc:mysql://120.78.156.24:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: myuser
    password: 123456
redis:
  # database:
  host: 120.78.156.24
  port: 6379
  pool:
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 0
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
